# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Dilbert
version:      1.09
version_from: lib/WWW/Dilbert.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           0
    Image::Info:                   0
    LWP::Simple:                   0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
